language: objective-c
osx_image: xcode8
script:
  - xcodebuild -version
  - xcodebuild -project Example/FlowingMenuExample.xcodeproj -scheme FlowingMenuTests -sdk iphonesimulator -destination "OS=9.3,name=iPad 2" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
after_success:
  - bash <(curl -s https://codecov.io/bash) - cF iOS
